os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.3
env:
  - FIXTURE_PATH="`pwd`/Tests/SourceKittenDaemonTests/Fixtures" FIXTURE_PROJECT_DIR="`pwd`/Tests/SourceKittenDaemonTests/Fixtures/Project" FIXTURE_PROJECT_FILE_PATH="`pwd`/Tests/SourceKittenDaemonTests/Fixtures/Project/Fixture.xcodeproj"
script:
  - eval "$(curl -sL https://swift.vapor.sh/ci)"
matrix:
  allow_failures:
    - os: linux
